# Generated by Django 6.0.2 on 2026-03-09 13:35

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name="Profile",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("longest_days_inactive", models.IntegerField(default=0)),
                ("llm_chat_calls", models.IntegerField(default=0)),
                ("llm_task_calls", models.IntegerField(default=0)),
                ("llm_eval_calls", models.IntegerField(default=0)),
                ("problems_attempted", models.IntegerField(default=0)),
                ("unaided_solutions", models.IntegerField(default=0)),
                ("mastery_problems_attempted", models.IntegerField(default=0)),
                ("mastery_unaided_solutions", models.IntegerField(default=0)),
                ("knowledge_lvl", models.FloatField(default=0)),
                ("success_rate", models.FloatField(default=0)),
                ("mastery_rate", models.FloatField(default=0)),
                ("mastery_progress", models.FloatField(default=0)),
                ("mastery_lvl", models.IntegerField(default=0)),
                ("performance", models.FloatField(default=0)),
                ("engagement", models.FloatField(default=1)),
                (
                    "user",
                    models.OneToOneField(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="profile",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
        ),
        migrations.CreateModel(
            name="TopicStarted",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("topic", models.CharField(max_length=50)),
                (
                    "user",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="topics_started",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
        ),
        migrations.CreateModel(
            name="Knowledge",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("topic", models.CharField(max_length=50)),
                ("level", models.IntegerField(default=0)),
                (
                    "user",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="knowledge",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
            options={
                "unique_together": {("user", "topic")},
            },
        ),
    ]
